---
# handlers file for arillso.openvpn

- name: restart openvpn
  become: true
  service:
    name: openvpn
    state: restarted
    enabled: true

- name: start openvpn
  become: true
  service:
    name: openvpn
    state: started
    enabled: true
